### PR TITLE
New feature: check if an extension is already being installed by a dependency

### PR DESCRIPTION
**Pull request by macheitor**
This PR depends on PR https://github.com/HPCNow/easybuild-framework_2024/pull/5. Please, DO NOT MERGE this PR before merging PR https://github.com/HPCNow/easybuild-framework_2024/pull/5

This feature prints on terminal the extensions in exts_list that are already installed by a dependency.
Output example:

> == Checking installed extensions...
> 
> == credentials v2.0.2  in exts_list
> == credentials v2.0.1  in dependency
> 
> == zip v2.3.1  in exts_list
> == zip v2.3.0  in dependency
> 
> == INSTALLED EXTENSIONS CHECKED!

Steps to reproduce:

git clone -b easybuild-update-integration https://github.com/HPCNow/easybuild-framework_2024.git
cd easybuild-framework_2024
python3 -m venv .venv
. .venv/bin/activate
pip install -r requirements.txt
pip install easybuild-easyblocks easybuild-easyconfigs
pip install -e .
python3 easybuild/main.py "your-eb-recipie-path" --check-installed-exts

### CODE REVIEW

**Comment by dagonzalezfo** [comment]
Using pip install -e . it was not working correcly.
```
$ eb IRkernel-1.3.2-foss-2022a-R-4.2.1.eb --check-installed-exts
.
.
.
== Checking installed extensions...

== highr v0.11  in exts_list
== highr v0.11  in dependency

== repr v1.1.5  in exts_list
== repr v1.1.5  in dependency

== IRdisplay v1.1  in exts_list
== IRdisplay v1.1  in dependency

== pbdZMQ v0.3-9  in exts_list
== pbdZMQ v0.3-9  in dependency

== IRkernel v1.3.2  in exts_list
== IRkernel v1.3.2  in dependency

== INSTALLED DEPENDENCY EXTENSIONS CHECKED!
```
However, the mentioned extensions are not in any dependency, just in the bundle that we want to deploy.

**Comment by dagonzalezfo** [comment]
Solved with new commit: 
```
== highr v0.11  in exts_list
== highr v0.11  in dependency /home/dgonzalez/hpc-playground/hpcnow-repos/easybuild-framework_2024/.venv/easybuild/easyconfigs/r/R/R-4.4.1-gfbf-2023b.eb

== INSTALLED DEPENDENCY EXTENSIONS CHECKED
```

**Comment by dagonzalezfo** [comment]
This will be really helpfull when adding new bundles

**Comment by macheitor** [comment]
@dagonzalezfo  PR synced with latest changes of original easybuild repo. PR Ready to be tested

**Comment by dagonzalezfo** [comment]
Tested with R bundle, it works correctly

**Pull request closed without merging**
